//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.InstructorCoures = new HashSet<InstructorCoure>();
        }
    
        public int InstructorID { get; set; }
        public string FullName { get; set; }
        public string Picture { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime RegisterationDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> Rate { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual ICollection<InstructorCoure> InstructorCoures { get; set; }
    }
}
