//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorCoure
    {
        public InstructorCoure()
        {
            this.StudentIntakes = new HashSet<StudentIntake>();
        }
    
        public int InstructorCourseID { get; set; }
        public int InstructorID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool IsPaied { get; set; }
        public string ImgPath { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<StudentIntake> StudentIntakes { get; set; }
    }
}
