//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineSchoolEntities : DbContext
    {
        public OnlineSchoolEntities()
            : base("name=OnlineSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Choise> Choises { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<InstructorCoure> InstructorCoures { get; set; }
        public virtual DbSet<PDF> PDFs { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentIntake> StudentIntakes { get; set; }
        public virtual DbSet<StudentSegment> StudentSegments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
