//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF
    {
        public int PDFID { get; set; }
        public string Title { get; set; }
        public byte[] PDFMaterial { get; set; }
        public int SegmentID { get; set; }
    
        public virtual Segment Segment { get; set; }
    }
}
