//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.Choises = new HashSet<Choise>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionTitle { get; set; }
        public string Answer { get; set; }
        public int SegmentID { get; set; }
        public bool QuestionType { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Choise> Choises { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
