//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public Segment()
        {
            this.PDFs = new HashSet<PDF>();
            this.Questions = new HashSet<Question>();
            this.StudentSegments = new HashSet<StudentSegment>();
            this.Videos = new HashSet<Video>();
        }
    
        public int SegmentID { get; set; }
        public string SegmentName { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinScore { get; set; }
        public int InstructorCourseID { get; set; }
        public string TextContent { get; set; }
    
        public virtual ICollection<PDF> PDFs { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<StudentSegment> StudentSegments { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
