//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentIntake
    {
        public int StudentIntakeID { get; set; }
        public int StudentID { get; set; }
        public int InstructorCourseID { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual InstructorCoure InstructorCoure { get; set; }
        public virtual Student Student { get; set; }
    }
}
