//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSegment
    {
        public int StudentSegmentID { get; set; }
        public int StudentID { get; set; }
        public int SegmentID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Segment Segment { get; set; }
        public virtual Student Student { get; set; }
    }
}
