//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSchool.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Answers = new HashSet<Answer>();
            this.StudentIntakes = new HashSet<StudentIntake>();
            this.StudentSegments = new HashSet<StudentSegment>();
        }
    
        public int StudentID { get; set; }
        public string FullName { get; set; }
        public string Picture { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime RegisterationDate { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<StudentIntake> StudentIntakes { get; set; }
        public virtual ICollection<StudentSegment> StudentSegments { get; set; }
    }
}
